spring.application.name: ingester
spring.kafka:
  admin.fail-fast: true
  client-id: spring
  bootstrap-servers: localhost:29092
  producer:
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
  template.default-topic: tweets

aws.paramstore.enabled: true
aws.paramstore.fail-fast: true
aws.paramstore.prefix: /config
# secrets at /{prefix}/{name}{separator}{profile}/{property}
# see https://docs.spring.io/spring-cloud-aws/docs/current/2.2.6.RELEASE/reference/html/appendix.html


config:
  timeout: PT10S
  twitter.within: PT1H
  twitter.uri: https://api.twitter.com
  twitter.bearer: ${TWITTER_BEARER}
  twitter.query: >-
    lang:en
    -is:retweet
    (
      from:Accenture OR @Accenture OR to:Accenture
      OR from:AccentureUK OR @AccentureUK OR to:AccentureUK
      OR from:AccentureTech OR @AccentureTech OR to:AccentureTech
      OR from:AccentureOps OR @AccentureOps OR to:AccentureOps
      OR from:AccentureSecure OR @AccentureSecure OR to:AccentureSecure
    )

---
spring.config.activate.on-profile: dev
spring.config.import: optional:file:.env.dev[.properties]
