spring.application.name: ingester
spring.kafka:
  admin.fail-fast: true
  client-id: spring
  bootstrap-servers: localhost:29092
  producer:
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
  template.default-topic: tweets

config:
  timeout: PT30S
  twitter.within: PT1H
  twitter.uri: https://api.twitter.com
  twitter.query: >-
    lang:en
    -is:retweet
    (
      from:Accenture OR @Accenture OR to:Accenture
      OR from:AccentureUK OR @AccentureUK OR to:AccentureUK
      OR from:AccentureTech OR @AccentureTech OR to:AccentureTech
      OR from:AccentureOps OR @AccentureOps OR to:AccentureOps
      OR from:AccentureSecure OR @AccentureSecure OR to:AccentureSecure
    )
