name: Pulumi
on:
  push:
    # branches:
    #   - ${{ github.event.repository.default_branch }}

env:
  ENV: dev

permissions:
  id-token: write

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - ingester
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build package
        run: mvn --batch-mode package
        working-directory: ${{matrix.dir}}/app
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ${{matrix.dir}}/app/target/${{matrix.dir}}-*-aws.jar

  shared:
    name: Deploy Shared
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dir:
          - shared-network
          - shared-kafka
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - id: bootstrap-aws
        env:
          PULUMI_CONFIG_PASSPHRASE: ''
        with:
          command: preview
          expect-no-changes: true
          cloud-url: 'file://${{github.workspace}}'
          stack-name: bootstrap-00_aws-${{env.ENV}}
          work-dir: ${{github.workspace}}/bootstrap/00_aws/
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{steps.bootstrap-aws.outputs['aws ci role']}}
          aws-region: ${{ steps.bootstrap-aws.outputs['aws region'] }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{matrix.dir}}-inf-${{env.ENV}}
          work-dir: ./${{matrix.dir}}/inf
          cloud-url: ${{steps.bootstrap-aws.outputs['pulumi backend']}} 
          secrets-provider: ${{steps.bootstrap-aws.outputs['pulumi secrets provider']}}

  applications:
    name: Deploy Applications
    needs:
      - package
      - shared
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - ingester
          - snowflake
          # - hastags
          # - visualise
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/download-artifact@v3
        with:
          name: jar
          path: ${{matrix.dir}}/app/target/
      - id: bootstrap-aws
        uses: pulumi/actions@v3
        env:
          PULUMI_CONFIG_PASSPHRASE: ''
        with:
          command: preview
          expect-no-changes: true
          cloud-url: 'file://${{github.workspace}}'
          stack-name: bootstrap-00_aws-${{env.ENV}}
          work-dir: ${{github.workspace}}/bootstrap/00_aws/
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{steps.bootstrap-aws.outputs['aws ci role']}}
          aws-region: ${{steps.bootstrap-aws.outputs['aws region']}}
      - id: bootstrap-snowflake
        uses: pulumi/actions@v3
        with:
          command: preview
          expect-no-changes: true
          cloud-url: ${{steps.bootstrap-aws.outputs['pulumi backend']}} 
          secrets-provider: ${{steps.bootstrap-aws.outputs['pulumi secrets provider']}}
          stack-name: bootstrap-10_snowflake-${{env.ENV}}
          work-dir: ${{github.workspace}}/bootstrap/10_snowflake/
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{matrix.dir}}-inf-${{env.ENV}}
          work-dir: ./${{matrix.dir}}/inf
          cloud-url: ${{needs.bootstrap.outputs.cloud-url}} 
          secrets-provider: ${{needs.bootstrap.outputs.secrets-provider}}
        env:
          SNOWFLAKE_ACCOUNT: ${{steps.bootstrap-snowflake.outputs['snowflake account']}}
          SNOWFLAKE_USERNAME: ${{steps.bootstrap-snowflake.outputs['snowflake username']}}
          SNOWFLAKE_PASSWORD: ${{steps.bootstrap-snowflake.outputs['snowflake password']}}
          SNOWFLAKE_REGION: ${{steps.bootstrap-snowflake.outputs['snowflake region']}}
