name: Pulumi
on:
  push:
    # branches:
    #   - ${{ github.event.repository.default_branch }}

env:
  ENV: dev

permissions:
  id-token: write

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          # - hastags
          - ingester
          # - visualise
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build package
        run: mvn --batch-mode package
        working-directory: ${{matrix.dir}}/app
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ${{matrix.dir}}/app/target/${{matrix.dir}}-*-aws.jar


  deploy:
    name: Deploy
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          # - hastags
          - ingester
          # - visualise
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/download-artifact@v3
        with:
          name: jar
          path: ${{matrix.dir}}/app/target/
      - name: set bootstrap variables
        id: bootstrap
        run: |
          pulumi login file://..
          echo "::set-output name=cloud-url::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'bucket name'
          )"
          echo "::set-output name=secrets-provider::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'secrets provider'
          )"
          echo "::set-output name=ci-role::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'ci role'
          )"

          echo "::set-output name=region::$(
            pulumi config get --stack bootstrap-${{env.ENV}} aws-native:region
          )"
        env:
          PULUMI_CONFIG_PASSPHRASE: ''
        working-directory: bootstrap
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{steps.bootstrap.outputs.ci-role}}
          aws-region: ${{steps.bootstrap.outputs.region}}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{matrix.dir}}-${{env.ENV}}
          work-dir: ./${{matrix.dir}}/inf
          cloud-url: ${{steps.bootstrap.outputs.cloud-url}} 
          secrets-provider: ${{steps.bootstrap.outputs.secrets-provider}} 
