name: Pulumi
on:
  push:
    # branches:
    #   - ${{ github.event.repository.default_branch }}

env:
  ENV: dev

permissions:
  id-token: write

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          # - hastags
          - ingest
          # - visualise
    steps:
      - uses: actions/checkout@v2
      - name: set bootstrap variables
        id: bootstrap
        run: |
          pulumi login file://.
          echo "::set-output name=cloud-url::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'bucket name'
          )"
          echo "::set-output name=secrets-provider::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'secret provider'
          )"
          echo "::set-output name=ci-role::$(
            pulumi stack output --stack bootstrap-${{env.ENV}} 'ci role'
          )"

          pushd bootstrap/inf
            pulumi stack ls
          popd
          
          echo "::set-output name=region::$(
            pulumi config get --stack bootstrap-${{env.ENV}} aws-native:region
          )"
        env:
          PULUMI_CONFIG_PASSPHRASE: ''
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{steps.bootstrap.outputs.ci-role}}
          aws-region: ${{steps.bootstrap.outputs.region}}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{matrix.dir}}-${{env.ENV}}
          work-dir: ${{matrix.dir}}/inf
          cloud-url: ${{steps.bootstrap.outputs.cloud-url}} 
          secrets-provider: ${{steps.bootstrap.outputs.secrets-provider}} 
